[package]
name = "hello_package"
version = "0.1.0"
authors = ["Abhi"]
edition = "2018"

[lib]
name = "banking"
path = "src/banking.rs"

[[bin]]
name = "main"
path = "src/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
